name: API-Import-POC

on:
  workflow_dispatch:
permissions:                
  contents: write           
  pull-requests: write 
jobs:
  Call_Main_CI_Workflow:
    uses: Lamintun/distributed-repo-base/.github/workflows/rw-ci-workflow.yml@main
    with:
      TLA: 'LMT'
      Repository: 'Lamintun/distributed-repo-branch-a'
      # repo-token: ${{ secrets.GITHUB_TOKEN }}
      # repo-name: 'distributed-repo-base'
      # repo-owner: 'Lamintun'
      # branch: 'main'
      # workflow-file: 'rw-ci-workflow.yml'
      # workflow-inputs: 'api-import-poc'
